name: Control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest

      - name: Run flake8
        uses: py-actions/flake8@v2

